version: '3'

services:
    api:
        restart: always
        build: 
            context: ./ 
            dockerfile: Dockerfile   
        container_name: django
        volumes:
            - web-django:/usr/src/app
            - web-static:/usr/src/app/static
        command: python /src/manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - migration
        networks: 
            - api

    mongodb:
        restart: unless-stopped
        image: mongo:latest
        container_name: mongo
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: dockerpswd
            MONGO_INITDB_DATABASE: pe_database
            MONGODB_DATABASE: pe_database
            MONGO_DATA_DIR: /data/db
            MONGO_LOG_DIR: /dev/null
        volumes:
            - data-volume:/data/db
        ports:
            - 27017:27017
        networks:
            - api

    migration:
        build: .
        command: python manage.py migrate
        volumes:
            - .:/web-django
        depends_on:
            - make_migrations
        networks:
            - api        

    make_migrations:
        build: .
        command: python manage.py makemigrations
        volumes:
            - .:/web-django
        depends_on:
            - mongodb
        networks:
            - api

networks: 
    api:
        driver: bridge

volumes:
    web-django:
    web-static: 
    data-volume:

