version: '3.3'
services:
    api:
        restart: always
        build: 
            context: ./ 
            dockerfile: Dockerfile        
        container_name: django
        dns:
            - 8.8.8.8
        volumes:
                - web-django:/usr/src/app
                - web-static:/usr/src/app/static
        
        command: python /src/manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        links:
            - mongo:mongo
    mongo:
        restart: always
        image: mongo:4.2
        container_name: mongo
        environment:
            - MONGODB_ROOT_PASSWORD=dockerpswd
            - MONGODB_NAME=PEDB          
            - MONGODB_USER=root
            - MONGODB_PASSWORD=dockerpswd
            - MONGODB_PORT=27017
            - MONGODB_SERVICE=localhost
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db
volumes:
    web-django:
    web-static:
    data-volume:
