version: '3'

services:
    mongodb:
        restart: always
        image: mongo:latest        
        container_name: mongo
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: dockerpswd
            MONGO_INITDB_DATABASE: pe_database
        hostname: mongodb-server
        volumes:
            - ./PEBackend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - data-volume:/data/db
        ports:
            - "27017:27017"
        networks:
            - backend

    migration:
        build: ./PEBackend
        command: bash -c " sleep 12 &&
            python manage.py makemigrations &&
            python manage.py migrate"
        volumes:
            - ./PEBackend:/web-django
        depends_on:
            - mongodb
        networks:
            - backend

    initialization:
        build: ./PEBackend
        command: bash -c " sleep 20 &&
            python manage.py runscript populate-Database"
        volumes:
            - ./PEBackend:/web-django
        depends_on:
            - mongodb
            - migration
        networks:
            - backend

    api:
        restart: always
        build: 
            context: ./PEBackend/ 
            dockerfile: Dockerfile   
        container_name: django
        volumes:
            - web-django:/usr/src/PEBackend
            - web-static:/usr/src/static
        ports:
            - "8000:8000"
        depends_on:
            - migration
        networks: 
            - backend
            - frontend

    front:
        restart: always
        depends_on: 
            - api
        container_name: pe_front
        build:
            context: ./front
            dockerfile: Dockerfile
        volumes:
            - ./front:/PE_ICC/front
            - '/PE_ICC/front/node_modules'
        ports:
            - "80:4200"
        networks:
            - frontend

networks: 
    backend:
        driver: bridge
    frontend:
        driver: bridge

volumes:
    web-django:
    web-static: 
    data-volume:
