# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.IntegerField()),
                ('top', models.IntegerField()),
                ('left', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
            options={
                'db_table': 'click',
                'managed': True,
            },
        ),
    ]
