# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('imageUrl', models.CharField(max_length=255)),
                ('algorithmiaCount', models.IntegerField()),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
    ]
